import csv
import json
import os
import requests

# URL CSV dari repository sumber (contoh Transfermarkt dataset)
CSV_URL = "https://raw.githubusercontent.com/salimt/football-datasets/refs/heads/main/datalake/transfermarkt/player_profiles/player_profiles.csv"

OUTPUT_FOLDER = "data_output"

# Buat folder output jika belum ada
os.makedirs(OUTPUT_FOLDER, exist_ok=True)

# Unduh CSV
print("📥 Downloading CSV...")
response = requests.get(CSV_URL)
response.raise_for_status()
csv_data = response.text.splitlines()

# Parsing CSV
reader = csv.DictReader(csv_data)

print("🔁 Converting CSV rows to JSON files...")
for row in reader:
    name = row.get("name") or "unknown_player"
    club = row.get("club_name") or "unknown_club"
    
    # Bersihkan nama file
    safe_name = name.replace("/", "-").replace(" ", "_").lower()
    safe_club = club.replace("/", "-").replace(" ", "_").lower()
    
    # Buat folder berdasarkan klub
    club_folder = os.path.join(OUTPUT_FOLDER, safe_club)
    os.makedirs(club_folder, exist_ok=True)
    
    # Simpan JSON 1 pemain = 1 file
    output_path = os.path.join(club_folder, f"{safe_name}.json")
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(row, f, ensure_ascii=False, indent=2)

print("✅ Done! JSON saved in", OUTPUT_FOLDER)
