name: Generate and deploy JSON datasets

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"  # Setiap minggu (hari Minggu, jam 00:00 UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run JSON generator
        run: |
          echo "Menjalankan konversi CSV ke JSON..."
          python auto_generate_json.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Menyiapkan konfigurasi Git..."
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          echo "Menambahkan file baru..."
          git add data_output/ || true

          echo "Membuat commit..."
          git commit -m "Auto update JSON datasets" || echo "No changes to commit"

          echo "Sinkronisasi sebelum push..."
          git pull --rebase

          echo "Mengirim ke repo..."
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
