name: Generate and deploy JSON datasets

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"  # Setiap minggu

permissions:
  contents: write  # wajib agar bisa push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository dengan credential aktif
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      # Konfigurasi Git
      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install dependencies
      - name: Install dependencies
        run: pip install requests

      # Jalankan script Python
      - name: Generate JSON files
        run: python auto_generate_json.py

      # Debug info (optional, biar tahu kalau masih error)
      - name: Debug Git state
        run: |
          git status
          git branch -a
          git remote -v

      # Commit dan push perubahan
      - name: Commit and push
  env:
    PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
  run: |
    git config --global user.name "github-actions"
    git config --global user.email "actions@github.com"

    git add data_output/ || true
    git diff --cached --quiet || git commit -m "Auto update JSON datasets"
    git push https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }} HEAD:main
