name: Generate and deploy json datasets

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"  # setiap minggu otomatis update

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run JSON generator
        run: python auto_generate_json.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data_output/
          git commit -m "Auto update JSON" || echo "No changes to commit"
          git push
