name: Generate and deploy league JSON datasets

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"  # Setiap minggu

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      # Setup Git
      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install dependencies
      - name: Install dependencies
        run: pip install requests

      # Generate JSON per liga
      - name: Generate league JSON files
        run: python auto_generate_json.py

      # Commit & push changes with PAT
      - name: Commit and push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git add data_output/
          git commit -m "Auto update league JSON datasets" || echo "No changes to commit"
          git pull --rebase
          git push https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }} HEAD:main